create database  shop charset=utf8;
use shop;
select  *  from product  where name like  '%名字%'
SET SESSION FOREIGN_KEY_CHECKS=0;

/* Drop Indexes */

DROP INDEX ORDERID_INDEX ON ORDERS;
DROP INDEX PRODUCTID_INDEX ON PRODUCT;
DROP INDEX INDEX_ID ON USERS;



/* Drop Views */

DROP VIEW PRODUCTINFOBYTYPE;



/* Drop Tables */

DROP TABLE ORDERITEMS;
DROP TABLE ORDERS;
DROP TABLE ADDRESS;
DROP TABLE PRODUCTIMAGE;
DROP TABLE PRODUCTMODELTYPE;
DROP TABLE PRODUCT;
DROP TABLE PRODUCTTYPE;
DROP TABLE USERS;




/* Create Tables */

-- 收货地址表
CREATE TABLE ADDRESS
(
	ADDRESSID INT NOT NULL AUTO_INCREMENT COMMENT '地址编号',
	PROVINCE VARCHAR(20) NOT NULL UNIQUE COMMENT '省份',
	CITY VARCHAR(20) NOT NULL COMMENT '城市',
	AREA VARCHAR(20) NOT NULL COMMENT '区域',
	STREET VARCHAR(200) COMMENT '街道',
	DETAIL VARCHAR(200) COMMENT '详细',
	TEL VARCHAR(11) NOT NULL COMMENT '电话',
	USER VARCHAR(20) COMMENT '联系人',
	USERID INT NOT NULL COMMENT '用户编号',
	PRIMARY KEY (ADDRESSID)
) COMMENT = '收货地址表 : 收货地址表';


-- 订单详情信息表
CREATE TABLE ORDERITEMS
(
	ORDERITEMID INT NOT NULL AUTO_INCREMENT COMMENT '编号',
	COUNT INT NOT NULL COMMENT '数量',
	DISCOUNT FLOAT NOT NULL COMMENT '折扣',
	ORDERID INT NOT NULL COMMENT '订单编号',
	PRODUCTID INT NOT NULL COMMENT '商品编号',
	PRIMARY KEY (ORDERITEMID)
) COMMENT = '订单详情表 : 订单详情信息表';


-- 存储订单信息的表
CREATE TABLE ORDERS
(
	ORDERID INT NOT NULL AUTO_INCREMENT COMMENT '编号',
	TIME DATETIME NOT NULL COMMENT '时间',
	STATUS INT NOT NULL COMMENT '状态',
	USERID INT NOT NULL COMMENT '用户编号',
	ADDRESSID INT NOT NULL COMMENT '地址编号',
	PRIMARY KEY (ORDERID)
) COMMENT = '订单表 : 存储订单信息的表';


-- 商品详情表
CREATE TABLE PRODUCT
(
	PRODUCTID INT NOT NULL AUTO_INCREMENT COMMENT '编号',
	NAME VARCHAR(100) NOT NULL COMMENT '商品名字',
	BRAND VARCHAR(20) NOT NULL COMMENT '品牌',
	TYPE VARCHAR(10) NOT NULL COMMENT '适合人群',
	SERIS VARCHAR(20) NOT NULL COMMENT '分类',
	IMAGE VARCHAR(500) NOT NULL COMMENT '商品首图',
	DESCRIPTION VARCHAR(1000) COMMENT '描述',
	BASICPRICE FLOAT NOT NULL COMMENT '价格',
	TYPEID INT NOT NULL COMMENT '类型编号',
	PRIMARY KEY (PRODUCTID)
) COMMENT = '商品表 : 商品详情表';


-- 存储图片路径的表
CREATE TABLE PRODUCTIMAGE
(
	PRODUCTIMAGEID INT NOT NULL AUTO_INCREMENT COMMENT '编号',
	PATH VARCHAR(1000) NOT NULL COMMENT '图片路径',
	ENABLE BIT(1) NOT NULL COMMENT '是否可用',
	PRODUCTID INT NOT NULL COMMENT '商品编号',
	PRIMARY KEY (PRODUCTIMAGEID)
) COMMENT = '商品图片表 : 存储图片路径的表';


-- 存储商品不同型号信息的表
CREATE TABLE PRODUCTMODELTYPE
(
	MODELTYPEID INT NOT NULL AUTO_INCREMENT COMMENT '型号编号',
	SIZE VARCHAR(20) NOT NULL COMMENT '尺寸',
	COLOR VARCHAR(20) NOT NULL COMMENT '颜色',
	PRICE FLOAT NOT NULL COMMENT '价格',
	COUNTS INT COMMENT '库存',
	PRODUCTID INT NOT NULL COMMENT '商品编号',
	PRIMARY KEY (MODELTYPEID)
) COMMENT = '商品型号详情表 : 存储商品不同型号信息的表';


-- 存储商品类型的表
CREATE TABLE PRODUCTTYPE
(
	PRODUCTTYPEID INT NOT NULL AUTO_INCREMENT COMMENT '编号',
	TYPENAME VARCHAR(20) NOT NULL COMMENT '类型名',
	PRIMARY KEY (PRODUCTTYPEID)
) COMMENT = '商品类型表 : 存储商品类型的表';


-- 这是存储用户信息的表
CREATE TABLE USERS
(
	USERID INT NOT NULL AUTO_INCREMENT COMMENT '用户编号',
	USERNAME VARCHAR(20) NOT NULL UNIQUE COMMENT '用户名',
	PASSWORD VARCHAR(30) NOT NULL COMMENT '密码',
	REALNAME VARCHAR(20) NOT NULL COMMENT '真实姓名',
	SEX BIT(1) COMMENT '性别',
	AGE INT COMMENT '年龄',
	IMAGE VARCHAR(50) COMMENT '头像',
	STATUS BIT(1) COMMENT '状态',
	PRIMARY KEY (USERID)
) COMMENT = '用户信息表 : 这是存储用户信息的表' DEFAULT CHARACTER SET utf8 COLLATE utf8_bin;



/* Create Foreign Keys */

ALTER TABLE ORDERS
	ADD FOREIGN KEY (ADDRESSID)
	REFERENCES ADDRESS (ADDRESSID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE ORDERITEMS
	ADD FOREIGN KEY (ORDERID)
	REFERENCES ORDERS (ORDERID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE ORDERITEMS
	ADD FOREIGN KEY (PRODUCTID)
	REFERENCES PRODUCT (PRODUCTID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE PRODUCTIMAGE
	ADD FOREIGN KEY (PRODUCTID)
	REFERENCES PRODUCT (PRODUCTID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE PRODUCTMODELTYPE
	ADD FOREIGN KEY (PRODUCTID)
	REFERENCES PRODUCT (PRODUCTID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE PRODUCT
	ADD FOREIGN KEY (TYPEID)
	REFERENCES PRODUCTTYPE (PRODUCTTYPEID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE ADDRESS
	ADD FOREIGN KEY (USERID)
	REFERENCES USERS (USERID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE ORDERS
	ADD FOREIGN KEY (USERID)
	REFERENCES USERS (USERID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;



/* Create Views */

CREATE  or replace VIEW PRODUCTINFOBYTYPE AS
select p.productId,name,brand,type,seris,description,basicprice,image,producttypeid,typename  from  product as p ,productType as pt 

where p.typeid=pt.producttypeid 
/* Create Indexes */

CREATE UNIQUE INDEX ORDERID_INDEX USING BTREE ON ORDERS (ORDERID DESC);
CREATE UNIQUE INDEX PRODUCTID_INDEX USING BTREE ON PRODUCT (PRODUCTID ASC);
CREATE UNIQUE INDEX INDEX_ID USING BTREE ON USERS (USERID DESC);

alter  table  product 
modify  IMAGE VARCHAR(500) NOT NULL COMMENT '商品首图';


alter table product 
add  discount float;;
alter  table  orders
add message varchar(2000)

